// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./components/Editor.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Formily: typeof import('./components/Formily.vue')['default']
    RenderComponent: typeof import('./components/RenderComponent.vue')['default']
    ScreenAdapter: typeof import('./components/ScreenAdapter.vue')['default']
  }
}

export { }
